spring:
  application:
    name: auth
  datasource:
    url: jdbc:postgresql://localhost:5432/plan_everything_accounts
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    properties.hibernate.dialect: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
server:
  port: 5000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5001/eureka/
security:
  admin:
    fullName: Администратор Администраторов
    email: admin@mail.ru
