server:
  port: 8080
spring:
  application:
    name: gateway-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5001/eureka/
security:
  oauth2:
    client:
      clientId: gateway-service
      clientSecret: gateway-service
      accessTokenUri: http://localhost:5000/oauth/token
      grant-type: client_credentials
      scope: all
    resource:
      user-info-uri: http://localhost:5000/accounts/principal
zuul:
  ignored-services: '*'
  sensitive-headers: Cookie,Set-Cookie
  routes:
    auth:
      url: http://localhost:5000
    projects:
      url: http://localhost:8081
    tasks:
      url: http://localhost:8082
    criteria:
      url: http://localhost:8083
    tags:
      url: http://localhost:8084
    members:
      url: http://localhost:8085
    events:
      url: http://localhost:8086
