server:
  port: 8084
spring:
  application:
    name: tags-service
  datasource:
      url: jdbc:postgresql://localhost:5432/plan_everything_tags
      username: postgres
      password: postgres
security:
  oauth2:
    client:
      clientId: tags-service
      clientSecret: tags-service
      accessTokenUri: http://localhost:5000/oauth/token
      grant-type: client_credentials
      scope: all
    resource:
      user-info-uri: http://localhost:5000/users/current
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5001/eureka/
