server:
  port: 8082
spring:
  application:
    name: tasks-service
  datasource:
      url: jdbc:postgresql://localhost:5432/plan_everything_tasks
      username: postgres
      password: postgres
security:
  oauth2:
    client:
      clientId: tasks-service
      clientSecret: tasks-service
      accessTokenUri: http://localhost:5000/oauth/token
      grant-type: client_credentials
      scope: all
    resource:
      user-info-uri: http://localhost:5000/accounts/principal
eureka:
  client:
    service-url:
      defaultZone: http://localhost:5001/eureka/
